mkdir "./type-challenges/$1"
touch "./type-challenges/$1/template.ts"
touch "./type-challenges/$1/test-cases.ts"
touch "./type-challenges/$1/README.md"
echo "<div style='width: 100%; margin: 0 auto;'><a href='https://github.com/type-challenges/type-challenges/blob/main/questions/$2-$1/README.md' target='_blank'><img src='https://img.shields.io/badge/' alt='·' /></a></div>" >> "./type-challenges/$1/README.md"
echo "\n# 题目注解" >> "./type-challenges/$1/README.md"
echo "成功创建题目 $1，冲～"